- name: ARINC_SENDER
  additional_h_files: ['<arinc653/queueing.h>', '<arinc653/sampling.h>', '<port_info.h>']
  state_struct:
      port_name: NAME_TYPE
      port_direction: PORT_DIRECTION_TYPE
      overhead: unsigned
      port_max_message_size: MESSAGE_SIZE_TYPE
      is_queuing_port: int
      q_port_max_nb_messages: MESSAGE_RANGE_TYPE

      #not inited
      port_id: APEX_INTEGER
      port_buffer: sys_port_data_t *

  init_func: arinc_sender_init
  activity: arinc_sender_activity

  out_ports:
      - name: portA
        type: send_net_data


- name: ARINC_RECEIVER
  additional_h_files: ['<arinc653/queueing.h>', '<arinc653/sampling.h>', '<port_info.h>']
  state_struct:
      port_name: NAME_TYPE
      port_direction: PORT_DIRECTION_TYPE
      port_max_message_size: MESSAGE_SIZE_TYPE
      is_queuing_port: int
      q_port_max_nb_messages: MESSAGE_RANGE_TYPE
      #not inited
      port_id: APEX_INTEGER

  init_func: arinc_receiver_init

  in_ports:
      - name: portA
        type: simple_send_data
        implementation:
            send: arinc_receive_message
