- name: ARINC_SENDER
  additional_h_files: ['arinc653/queueing.h', 'arinc653/sampling.h']
  state_struct:
      port_name: NAME_TYPE
      port_direction: PORT_DIRECTION_TYPE
      overhead: unsigned
      port_max_message_size: MESSAGE_SIZE_TYPE
      is_queuing_port: int
      q_port_max_nb_messages: MESSAGE_RANGE_TYPE

      #not inited
      port_id: APEX_INTEGER

  init_func: arinc_sender_init
  activity: arinc_sender_activity
  #in_ports:
  #    - name: portC
  #      type: send_flush_t
  #      implementation:
  #          send: x_send
  #          flush: x_flush
