- name: MAC_SENDER
  #additional_h_files: ['<port_info.h>']
  state_struct:
      src_mac[6]: uint8_t

  in_ports:
      - name: portA
        type: mac_send_data
        implementation:
            mac_send: mac_send
            flush: mac_flush
  out_ports:
      - name: portB
        type: send_net_data

- name: MAC_RECEIVER
  #additional_h_files: ['<port_info.h>']
  state_struct:
      src_mac[6]: uint8_t

  in_ports:
      - name: portA
        type: simple_send_data
        implementation:
            send: mac_receive
   #out_ports:
   #   - name: portB
   #      type: send_net_data
