instances:
    - name: arinc_port_rdr_1
      type: ARINC_PORT_READER
      state:
          port_name: '"UOUT"'
          port_direction: DESTINATION
          prepend_overhead: 42 #14+20+8
          append_overhead: 1
          port_max_message_size: 64
          is_queuing_port: 1
          q_port_max_nb_messages: 10

    - name: arinc_port_rdr_2
      type: ARINC_PORT_READER
      state:
          port_name: '"UOUT2"'
          port_direction: DESTINATION
          prepend_overhead: 42 #14+20+8
          append_overhead: 1
          port_max_message_size: 64
          is_queuing_port: 1
          q_port_max_nb_messages: 10

    - name: afdx_filler_1
      type: AFDX_FILLER
      state:
          vl_id: 1
          ttl: 5
          src_partition_id: 1
          dst_partition_id: 2
          src_afdx_port: 0
          dst_afdx_port: 1
          type_of_packet: UNICAST_PACKET

    - name: afdx_filler_2
      type: AFDX_FILLER
      state:
          vl_id: 2
          ttl: 5
          src_partition_id: 1
          dst_partition_id: 2
          src_afdx_port: 1
          dst_afdx_port: 2
          type_of_packet: UNICAST_PACKET

    - name: afdx_enqr_1
      type: AFDX_QUEUE_ENQUEUER
      state:
          BAG: SECOND
          max_queue_size: 10

    - name: afdx_enqr_2
      type: AFDX_QUEUE_ENQUEUER
      state:
          BAG: SECOND
          max_queue_size: 10

    - name: virtio_net_dev_1
      type: VIRTIO_NET_DEV
      state:
          pci_bus: 0
          pci_dev: 1
          pci_fn: 0

    - name: virtio_net_dev_2
      type: VIRTIO_NET_DEV
      state:
          pci_bus: 0
          pci_dev: 2
          pci_fn: 0

    - name: afdx_stop_send_1
      type: AFDX_STOP

links:
#vl 1
    - from:
        instance: arinc_port_rdr_1
        port: portA
      to:
        instance: afdx_filler_1
        port: portA

    - from:
        instance: afdx_filler_1
        port: portB
      to:
        instance: afdx_enqr_1
        port: portB

    - from:
        instance: afdx_enqr_1
        port: portNetA
      to:
        instance: virtio_net_dev_1
        port: portA

    - from:
        instance: afdx_enqr_1
        port: portNetB
      to:
        instance: virtio_net_dev_2
        port: portA
 #vl 2
    - from:
        instance: arinc_port_rdr_2
        port: portA
      to:
        instance: afdx_filler_2
        port: portA

    - from:
        instance: afdx_filler_2
        port: portB
      to:
        instance: afdx_enqr_2
        port: portB

    - from:
        instance: afdx_enqr_2
        port: portNetA
      to:
        instance: virtio_net_dev_1
        port: portA

    - from:
        instance: afdx_enqr_2
        port: portNetB
      to:
        instance: virtio_net_dev_2
        port: portA

#receive
    - from:
        instance: virtio_net_dev_1
        port: portB
      to:
        instance: afdx_stop_send_1
        port: portA
    - from:
        instance: virtio_net_dev_2
        port: portB
      to:
        instance: afdx_stop_send_1
        port: portA
