- name: AFDX_FILLER
  additional_h_files: ['<stdint.h>', '<arinc653/queueing.h>', '<arinc653/sampling.h>', '<afdx/AFDX_ES_config.h>', '<afdx/AFDX_filling.h>', '<net/byteorder.h>', '<string.h>', '<stdio.h>']
  state_struct:
      # vl identificator
        vl_id: uint16_t
        ttl: uint8_t
        src_partition_id: uint8_t
        dst_partition_id: uint8_t
        src_afdx_port: uint16_t
        dst_afdx_port: uint16_t
        sn: uint8_t
        type_of_packet: PACKET_TYPE

# init_func: afdx_filler_init

  in_ports:
      - name: portA
        type: preallocated_sender
        implementation:
           send: afdx_filler_send
           flush: afdx_filler_flush

  out_ports:
       - name: portB
         type: afdx_queue_enqueuer

- name: AFDX_QUEUE_ENQUEUER
  additional_h_files: ['<stdint.h>', '<afdx/AFDX_ES_config.h>', '<afdx/AFDX_frame.h>', '<afdx/AFDX_filling.h>', '<afdx/AFDX_ES.h>', '<afdx/AFDX_ES_config.h>']
  state_struct:
        BAG: pok_time_t
        queue[15200]: uint8_t

  init_func: afdx_queue_init
  activity: afdx_queue_enqueuer_activity

  in_ports:
      - name: portB
        type: afdx_queue_enqueuer
        implementation:
            afdx_add_to_queue: afdx_enqueuer_implementation

  out_ports:
      - name: portNetA
        type: preallocated_sender

      - name: portNetB
        type: preallocated_sender
