- name: DTSEC_NET_DEV
  additional_h_files: ['"dtsec_state.h"']
  state_struct:
      dtsec_num: uint8_t
      dev_state: struct dev_state

  init_func: dtsec_component_init
  activity:  dtsec_receive_activity

  memory_blocks:
      - name: PPC_FMan
        size: "0x100000"
        #physical_address: "$bsp.FMan"
        physical_address: "0xfe400000"
        contiguous: true
        cachepolicy: IO

      - name: Heap
        size: "0x10000"
        contiguous: true
        cachepolicy: IO
        is_per_instance: true


  in_ports:
      - name: portA
        type: preallocated_sender
        implementation:
            send: dtsec_send_frame
            flush: dtsec_flush_send

  out_ports:
      - name: portB
        type: message_handler
