- name: Y
  #additional_h_files: ['y.h'] #list of additional headers
  state_struct:
      - type: int
        name: y
  #init_func: optional
  in_ports:
      - name: portA
        type: tick_t
        implementation:
            tick: y_tick
  out_ports:
      - name: portB
        type: send_flush_t
