components:
    - type : X
      instances:
        - name: x_1
          state:
              x: 1

        - name: x_2
          state:
              x: 2

    - type: Y
      instances:
        - name: y_1
          state:
              y: 1

        - name: y_2
          state:
              y: 2

    - type: ARINC_SENDER
      instances:
        - name:
            arinc_sender_1
          state:
              port_name: '"UOUT"'
              port_direction: DESTINATION
              overhead: 42 #14+20+8
              port_max_message_size: 64
              is_queuing_port: 1
              q_port_max_nb_messages: 10

    - type: UDP_IP_SENDER
      instances:
        - name:
            udp_ip_sender_1
          state:
              src_ip: IP_ADDR(192, 168, 56, 101)
              src_port: 10002
              dst_ip: IP_ADDR(192, 168, 56, 1)
              dst_port: 10003
              dst_mac: '{0x08, 0x00, 0x27, 0x00, 0x88, 0xAD}'

    - type: MAC_SENDER
      instances:
        - name: mac_sender_1
          state:
              src_mac: '{0x52, 0x54, 0x00, 0x01, 0x02, 0x03}'

    - type: VIRTIO_NET_DEV
      instances:
        - name: virtio_net_dev_1

    - type: ARP_ANSWERER
      instances:
          - name: arp_answerer_1
            state:
                good_ips: '{IP_ADDR(192, 168, 56, 101),IP_ADDR(192, 168, 56, 102)}'
                good_ips_len: 2
                src_mac: '{0x52, 0x54, 0x00, 0x01, 0x02, 0x03}'

    - type: MAC_RECEIVER
      instances:
          - name: mac_receiver_1
            state:
                my_mac: '{0x52, 0x54, 0x00, 0x01, 0x02, 0x03}'

    - type: UDP_RECEIVER_FILTER
      instances:
          - name: udp_receiver_filter_1
            state:
                good_ip_port: '{{IP_ADDR(192, 168, 56, 101), 10001},{IP_ADDR(192, 168, 56, 102), 10005}}'
                good_ip_port_len: 2

links:
    - from:
          instance: y_1
          port: portB
      to:
          instance: x_1
          port: portC

    - from:
          instance: y_2
          port: portB
      to:
          instance: x_2
          port: portC

    - from:
        instance: arinc_sender_1
        port: portA
      to:
        instance: udp_ip_sender_1
        port: portA

    - from:
        instance: udp_ip_sender_1
        port: portB
      to:
        instance: mac_sender_1
        port: portA

    - from:
        instance: mac_sender_1
        port: portB
      to:
        instance: virtio_net_dev_1
        port: portA

    - from:
        instance: virtio_net_dev_1
        port: portB
      to:
        instance: mac_receiver_1
        port: portA

    - from:
        instance: mac_receiver_1
        port: port_ARP
      to:
        instance: arp_answerer_1
        port: portA

    - from:
        instance: arp_answerer_1
        port: portB
      to:
        instance: mac_sender_1
        port: portA

    - from:
        instance: mac_receiver_1
        port: port_UDP
      to:
        instance: udp_receiver_filter_1
        port: portA

