components:
    - type : X
      instances:
        - name: x_1
          state:
              x: 1

        - name: x_2
          state:
              x: 2

    - type: Y
      instances:
        - name: y_1
          state:
              y: 1

        - name: y_2
          state:
              y: 2

    - type: ARINC_SENDER
      instances:
        - name:
            arinc_sender_1
          state:
              port_name: '"UOUT"'
              port_direction: DESTINATION
              overhead: 42 #14+20+8
              port_max_message_size: 64
              is_queuing_port: 1
              q_port_max_nb_messages: 10


links:
    - from:
          instance: y_1
          port: portB
      to:
          instance: x_1
          port: portC

    - from:
          instance: y_2
          port: portB
      to:
          instance: x_2
          port: portC

