- name: UDP_IP_SENDER
  additional_h_files: ['"ip_addr.h"']
  state_struct:
      src_ip: uint32_t
      src_port: uint16_t
      dst_ip: uint32_t
      dst_port: uint16_t
      dst_mac[6]: uint8_t

  in_ports:
      - name: portA
        type: send_net_data
        implementation:
            send: udp_ip_send
            flush: udp_ip_flush
  out_ports:
      - name: portB
        type: mac_send_data

- name: UDP_RECEIVER_FILTER
  in_ports:
      - name: portA
        type: simple_send_data
        implementation:
            send: udp_receive_and_filter
