- name: X
  #additional_h_files: ['x.h'] #list of additional headers
  state_struct:
      x: char
  init_func: x_init #optional
  in_ports:
      - name: portC
        type: send_flush_t
        implementation:
            send: x_send
            flush: x_flush
- name: X2
  state_struct:
      tmp: char
