- name: ARP_ANSWERER
  #additional_h_files: ['"arp_ip_list.h"']
  state_struct:
      good_ips[10]: uint32_t
      good_ips_len: uint32_t
  in_ports:
      - name: portA
        type: simple_send_data
        implementation:
            send: arp_receive

  out_ports:
      - name: portB
        type: mac_send_data
